/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BookRouteImport } from './routes/book'
import { Route as AccountIndexRouteImport } from './routes/account.index'
import { Route as AccountAddressesRouteImport } from './routes/account.addresses'
import { Route as AccountLoginRouteImport } from './routes/account.login'
import { Route as AccountVehiclesRouteImport } from './routes/account.vehicles'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminDetailersRouteImport } from './routes/admin.detailers'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as DTokenRouteImport } from './routes/d.$token'
import { Route as AccountBookingsIdRouteImport } from './routes/account.bookings.$id'
import { Route as AdminBookingsIdRouteImport } from './routes/admin.bookings.$id'
import { Route as AdminBookingsNewRouteImport } from './routes/admin.bookings.new'
import { Route as AdminDetailersIdRouteImport } from './routes/admin.detailers_.$id'
import { Route as AdminDetailersNewRouteImport } from './routes/admin.detailers_.new'
import { Route as DTokenBookingIdRouteImport } from './routes/d.$token_.$bookingId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountAddressesRoute = AccountAddressesRouteImport.update({
  id: '/account/addresses',
  path: '/account/addresses',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountLoginRoute = AccountLoginRouteImport.update({
  id: '/account/login',
  path: '/account/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountVehiclesRoute = AccountVehiclesRouteImport.update({
  id: '/account/vehicles',
  path: '/account/vehicles',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDetailersRoute = AdminDetailersRouteImport.update({
  id: '/admin/detailers',
  path: '/admin/detailers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DTokenRoute = DTokenRouteImport.update({
  id: '/d/$token',
  path: '/d/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountBookingsIdRoute = AccountBookingsIdRouteImport.update({
  id: '/account/bookings/$id',
  path: '/account/bookings/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBookingsIdRoute = AdminBookingsIdRouteImport.update({
  id: '/admin/bookings/$id',
  path: '/admin/bookings/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBookingsNewRoute = AdminBookingsNewRouteImport.update({
  id: '/admin/bookings/new',
  path: '/admin/bookings/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDetailersIdRoute = AdminDetailersIdRouteImport.update({
  id: '/admin/detailers_/$id',
  path: '/admin/detailers/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDetailersNewRoute = AdminDetailersNewRouteImport.update({
  id: '/admin/detailers_/new',
  path: '/admin/detailers/new',
  getParentRoute: () => rootRouteImport,
} as any)
const DTokenBookingIdRoute = DTokenBookingIdRouteImport.update({
  id: '/d/$token_/$bookingId',
  path: '/d/$token/$bookingId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/book': typeof BookRoute
  '/account/addresses': typeof AccountAddressesRoute
  '/account/login': typeof AccountLoginRoute
  '/account/vehicles': typeof AccountVehiclesRoute
  '/admin/detailers': typeof AdminDetailersRoute
  '/admin/login': typeof AdminLoginRoute
  '/d/$token': typeof DTokenRoute
  '/account/': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/account/bookings/$id': typeof AccountBookingsIdRoute
  '/admin/bookings/$id': typeof AdminBookingsIdRoute
  '/admin/bookings/new': typeof AdminBookingsNewRoute
  '/admin/detailers/$id': typeof AdminDetailersIdRoute
  '/admin/detailers/new': typeof AdminDetailersNewRoute
  '/d/$token/$bookingId': typeof DTokenBookingIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/book': typeof BookRoute
  '/account/addresses': typeof AccountAddressesRoute
  '/account/login': typeof AccountLoginRoute
  '/account/vehicles': typeof AccountVehiclesRoute
  '/admin/detailers': typeof AdminDetailersRoute
  '/admin/login': typeof AdminLoginRoute
  '/d/$token': typeof DTokenRoute
  '/account': typeof AccountIndexRoute
  '/admin': typeof AdminIndexRoute
  '/account/bookings/$id': typeof AccountBookingsIdRoute
  '/admin/bookings/$id': typeof AdminBookingsIdRoute
  '/admin/bookings/new': typeof AdminBookingsNewRoute
  '/admin/detailers/$id': typeof AdminDetailersIdRoute
  '/admin/detailers/new': typeof AdminDetailersNewRoute
  '/d/$token/$bookingId': typeof DTokenBookingIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/book': typeof BookRoute
  '/account/addresses': typeof AccountAddressesRoute
  '/account/login': typeof AccountLoginRoute
  '/account/vehicles': typeof AccountVehiclesRoute
  '/admin/detailers': typeof AdminDetailersRoute
  '/admin/login': typeof AdminLoginRoute
  '/d/$token': typeof DTokenRoute
  '/account/': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/account/bookings/$id': typeof AccountBookingsIdRoute
  '/admin/bookings/$id': typeof AdminBookingsIdRoute
  '/admin/bookings/new': typeof AdminBookingsNewRoute
  '/admin/detailers_/$id': typeof AdminDetailersIdRoute
  '/admin/detailers_/new': typeof AdminDetailersNewRoute
  '/d/$token_/$bookingId': typeof DTokenBookingIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/book'
    | '/account/addresses'
    | '/account/login'
    | '/account/vehicles'
    | '/admin/detailers'
    | '/admin/login'
    | '/d/$token'
    | '/account/'
    | '/admin/'
    | '/account/bookings/$id'
    | '/admin/bookings/$id'
    | '/admin/bookings/new'
    | '/admin/detailers/$id'
    | '/admin/detailers/new'
    | '/d/$token/$bookingId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/book'
    | '/account/addresses'
    | '/account/login'
    | '/account/vehicles'
    | '/admin/detailers'
    | '/admin/login'
    | '/d/$token'
    | '/account'
    | '/admin'
    | '/account/bookings/$id'
    | '/admin/bookings/$id'
    | '/admin/bookings/new'
    | '/admin/detailers/$id'
    | '/admin/detailers/new'
    | '/d/$token/$bookingId'
  id:
    | '__root__'
    | '/'
    | '/book'
    | '/account/addresses'
    | '/account/login'
    | '/account/vehicles'
    | '/admin/detailers'
    | '/admin/login'
    | '/d/$token'
    | '/account/'
    | '/admin/'
    | '/account/bookings/$id'
    | '/admin/bookings/$id'
    | '/admin/bookings/new'
    | '/admin/detailers_/$id'
    | '/admin/detailers_/new'
    | '/d/$token_/$bookingId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BookRoute: typeof BookRoute
  AccountAddressesRoute: typeof AccountAddressesRoute
  AccountLoginRoute: typeof AccountLoginRoute
  AccountVehiclesRoute: typeof AccountVehiclesRoute
  AdminDetailersRoute: typeof AdminDetailersRoute
  AdminLoginRoute: typeof AdminLoginRoute
  DTokenRoute: typeof DTokenRoute
  AccountIndexRoute: typeof AccountIndexRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AccountBookingsIdRoute: typeof AccountBookingsIdRoute
  AdminBookingsIdRoute: typeof AdminBookingsIdRoute
  AdminBookingsNewRoute: typeof AdminBookingsNewRoute
  AdminDetailersIdRoute: typeof AdminDetailersIdRoute
  AdminDetailersNewRoute: typeof AdminDetailersNewRoute
  DTokenBookingIdRoute: typeof DTokenBookingIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/': {
      id: '/account/'
      path: '/account'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/addresses': {
      id: '/account/addresses'
      path: '/account/addresses'
      fullPath: '/account/addresses'
      preLoaderRoute: typeof AccountAddressesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/login': {
      id: '/account/login'
      path: '/account/login'
      fullPath: '/account/login'
      preLoaderRoute: typeof AccountLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/vehicles': {
      id: '/account/vehicles'
      path: '/account/vehicles'
      fullPath: '/account/vehicles'
      preLoaderRoute: typeof AccountVehiclesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/detailers': {
      id: '/admin/detailers'
      path: '/admin/detailers'
      fullPath: '/admin/detailers'
      preLoaderRoute: typeof AdminDetailersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/d/$token': {
      id: '/d/$token'
      path: '/d/$token'
      fullPath: '/d/$token'
      preLoaderRoute: typeof DTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/bookings/$id': {
      id: '/account/bookings/$id'
      path: '/account/bookings/$id'
      fullPath: '/account/bookings/$id'
      preLoaderRoute: typeof AccountBookingsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/bookings/$id': {
      id: '/admin/bookings/$id'
      path: '/admin/bookings/$id'
      fullPath: '/admin/bookings/$id'
      preLoaderRoute: typeof AdminBookingsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/bookings/new': {
      id: '/admin/bookings/new'
      path: '/admin/bookings/new'
      fullPath: '/admin/bookings/new'
      preLoaderRoute: typeof AdminBookingsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/detailers_/$id': {
      id: '/admin/detailers_/$id'
      path: '/admin/detailers/$id'
      fullPath: '/admin/detailers/$id'
      preLoaderRoute: typeof AdminDetailersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/detailers_/new': {
      id: '/admin/detailers_/new'
      path: '/admin/detailers/new'
      fullPath: '/admin/detailers/new'
      preLoaderRoute: typeof AdminDetailersNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/d/$token_/$bookingId': {
      id: '/d/$token_/$bookingId'
      path: '/d/$token/$bookingId'
      fullPath: '/d/$token/$bookingId'
      preLoaderRoute: typeof DTokenBookingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BookRoute: BookRoute,
  AccountAddressesRoute: AccountAddressesRoute,
  AccountLoginRoute: AccountLoginRoute,
  AccountVehiclesRoute: AccountVehiclesRoute,
  AdminDetailersRoute: AdminDetailersRoute,
  AdminLoginRoute: AdminLoginRoute,
  DTokenRoute: DTokenRoute,
  AccountIndexRoute: AccountIndexRoute,
  AdminIndexRoute: AdminIndexRoute,
  AccountBookingsIdRoute: AccountBookingsIdRoute,
  AdminBookingsIdRoute: AdminBookingsIdRoute,
  AdminBookingsNewRoute: AdminBookingsNewRoute,
  AdminDetailersIdRoute: AdminDetailersIdRoute,
  AdminDetailersNewRoute: AdminDetailersNewRoute,
  DTokenBookingIdRoute: DTokenBookingIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
